# Generated by Django 5.0.4 on 2024-07-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='fullname',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(default='a', max_length=150),
            preserve_default=False,
        ),
    ]
