# Generated by Django 5.0.4 on 2024-09-06 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_remove_prescription_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptiondetail',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.prescription'),
        ),
    ]
