# Generated by Django 5.0.4 on 2024-10-03 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_alter_address_lga_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(default='Nigeria', on_delete=django.db.models.deletion.CASCADE, to='addresses.country'),
        ),
    ]
