# Generated by Django 5.0.4 on 2024-10-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_alter_address_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='address_info',
        ),
    ]
