# Generated by Django 5.0.4 on 2024-10-25 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0007_rename_address_info_address_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.lga'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.state'),
        ),
    ]
