# Generated by Django 5.0.4 on 2024-07-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='dispatch_status',
        ),
        migrations.AddField(
            model_name='order',
            name='dispatch_status',
            field=models.BooleanField(default=False),
        ),
    ]
