# Generated by Django 5.0.4 on 2024-07-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_delivery_dispatch_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='dispatch_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dispatch_status',
        ),
        migrations.AddField(
            model_name='order',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
