# Generated by Django 5.0.4 on 2024-08-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='VAT',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
