# Generated by Django 5.0.4 on 2024-08-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_vat_alter_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='item',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
