# Generated by Django 5.0.4 on 2024-08-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderdetail_item_alter_orderdetail_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='VAT',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
