# Generated by Django 5.0.4 on 2024-07-05 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_itemcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.itemcategory'),
            preserve_default=False,
        ),
    ]
