# Generated by Django 5.0.4 on 2024-09-12 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.usergroup'),
        ),
    ]
