# Generated by Django 5.0.4 on 2024-07-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinician',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
