# Generated by Django 5.0.4 on 2024-09-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_remove_prescription_item_prescriptiondetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='dose',
        ),
    ]
