# Generated by Django 5.1.3 on 2024-11-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0005_rename_dose_prescriptiondetail_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugtype',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
