# Generated by Django 5.1.3 on 2024-11-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0006_alter_drugtype_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptiondetail',
            name='dose',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
