# Generated by Django 5.1.3 on 2024-11-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0007_prescriptiondetail_dose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptiondetail',
            name='dose',
        ),
    ]
