# Generated by Django 5.0.4 on 2024-09-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0003_applicationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=15),
        ),
    ]
