# Generated by Django 5.0.4 on 2024-10-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0006_alter_applicationrequest_licence_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationrequest',
            name='licence_number',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
