# Generated by Django 5.0.4 on 2024-10-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
