# Generated by Django 5.0.4 on 2024-10-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderdetail_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billed',
            field=models.BooleanField(default=False),
        ),
    ]
